### ISSUE TITLE
error compiling the comctl132.dll

### ISSUE THREAD

**Issue by NakNak669** [Yet-Zio/WusaBypassUAC#1]
hey,

need help to compile the comctl132.dll .
i open the project in visual studio 2019 and try to compile i get error ( target missing executable)

help ?

**Comment by Yet-Zio** [comment]
Did you open as CMake Project and try reloading CMake cache? It's probably because you have to build it once or build was outputted somwhere else. I didn't use VS for this, so I can't help with it particularly.

**Comment by Yet-Zio** [comment]
Marking as closed for the time being. Hopefully fixed.
